### ISSUE TITLE
Can not view Applications.

### ISSUE THREAD

**Issue by MikhailVado** [porowns/kryptedauth#43] opened 2018-05-05 02:27 UTC
# Description of issue
 Unable to view applications unless they are directly linked to me.
# Steps
 Went to https://authv2.kryptedgaming.com/applications as directed that did not work, Tried applications/view/ and it said i do not have the permission to view, also clicked the applications button and it said i do not have the permission to view 
# Url
Please paste the URL that caused this issue.
 See above steps

**Comment by porowns** [comment] 2018-05-05 02:30
Permissions are working as intended, however, you shouldn't have been able to view the application without those permissions. Will work on a fix.

**Comment by MikhailVado** [comment] 2018-05-05 02:41
Upon looking into it further, I've gone to the direct link to the application which i can open but i am unable to open the API's the error message i get is You do not have permission to view that. <QuerySet [<Group: BYTE>, <Group: EVE>]>

**Comment by porowns** [comment] 2018-05-10 05:35
Fixed with
https://github.com/porowns/kryptedauth/commit/5bd813958fd35604b4b9481be234e22d77600ed8

**Closed by porowns** 2018-05-10 05:35 UTC
Labels: bug
